{
 "title": "HW5_Dashboard_Improted",
 "time": { "from": "2026-01-17T11:52:16.136Z", "to": "2026-01-17T13:39:29.084Z" },
 "panels": [
  {
   "title": "Latency (response time) by API method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, handler) (rate(http_request_duration_seconds_bucket{job=\"users-service\",\r\nhandler!~\"/(metrics|health|health/|cause-5xx)\"}[5m])))",
     "legendFormat": "{{handler}} p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, handler) (rate(http_request_duration_seconds_bucket{job=\"users-service\",\r\nhandler!~\"/(metrics|health|health/|cause-5xx)\"}[5m])))",
     "legendFormat": "{{handler}} p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le, handler) (rate(http_request_duration_seconds_bucket{job=\"users-service\",\r\nhandler!~\"/(metrics|health|health/|cause-5xx)\"}[5m])))",
     "legendFormat": "{{handler}} p99"
    },
    {
     "expr": "max by (handler) (rate(http_request_duration_seconds_bucket{job=\"users-service\",\r\nhandler!~\"/(metrics|health|health/|cause-5xx)\"}[5m]))",
     "legendFormat": "{{handler}} max"
    }
   ]
  },
  {
   "title": "Latency (response time) (Nginx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,\r\n  sum by (le) (\r\n    rate(nginx_ingress_controller_request_duration_seconds_bucket{\r\n      job=\"nginx-ingress-nginx-controller-metrics\",\r\n      exported_namespace=\"default\",\r\n      exported_service=\"users-service\"\r\n    }[5m])\r\n  )\r\n)",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95,\r\n  sum by (le) (\r\n    rate(nginx_ingress_controller_request_duration_seconds_bucket{\r\n      job=\"nginx-ingress-nginx-controller-metrics\",\r\n      exported_namespace=\"default\",\r\n      exported_service=\"users-service\"\r\n    }[5m])\r\n  )\r\n)",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99,\r\n  sum by (le) (\r\n    rate(nginx_ingress_controller_request_duration_seconds_bucket{\r\n      job=\"nginx-ingress-nginx-controller-metrics\",\r\n      exported_namespace=\"default\",\r\n      exported_service=\"users-service\"\r\n    }[5m])\r\n  )\r\n)",
     "legendFormat": "p99"
    },
    {
     "expr": "max(rate(nginx_ingress_controller_request_duration_seconds_bucket{\r\n      job=\"nginx-ingress-nginx-controller-metrics\",\r\n      exported_namespace=\"default\",\r\n      exported_service=\"users-service\"\r\n    }[5m]))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "RPS by API method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (handler) (\r\n  rate(http_requests_total{job=\"users-service\",\r\nhandler!~\"/(metrics|health|cause-5xx|health/)\"}[5m])\r\n)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "RPS (Nginx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\r\n  rate(nginx_ingress_controller_requests{job=\"nginx-ingress-nginx-controller-metrics\", exported_namespace=\"default\",\r\n  exported_service=\"users-service\",}[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate by API method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (handler) (\r\n  rate(http_requests_total{job=\"users-service\", handler!~\"/(metrics|health|health/)\", status=~\"5..\"}[5m])\r\n)\r\n/\r\nsum by (handler) (\r\n  rate(http_requests_total{job=\"users-service\", handler!~\"/(metrics|health|health/)\"}[5m])\r\n)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Error Rate (Nginx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\r\n  rate(nginx_ingress_controller_requests{\r\n    job=\"nginx-ingress-nginx-controller-metrics\",\r\n    exported_namespace=\"default\",\r\n    exported_service=\"users-service\",\r\n    status=~\"5..\"\r\n  }[5m])\r\n)\r\n/\r\nsum(\r\n  rate(nginx_ingress_controller_requests{\r\n    job=\"nginx-ingress-nginx-controller-metrics\",\r\n    exported_namespace=\"default\",\r\n    exported_service=\"users-service\"\r\n  }[5m])\r\n)",
     "legendFormat": "Error Rate"
    }
   ]
  }
 ]
}