apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hw3-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hw3-service
                port:
                  number: 80