apiVersion: v1
kind: ConfigMap
metadata:
  name: users-config
  namespace: default
data:
  DB_DRIVER_SYNC: "psycopg2"
  DB_DRIVER_ASYNC: "asyncpg"
  DB_HOST: "users-postgresql" # Имя PostgreSQL в кластере
  DB_PORT: "5432"             # Порт PostgreSQL